services:
#    torrent_request.example:
#        class: TorrentRequestBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    t411_manager:
        class: TorrentRequestBundle\Utils\T411Manager
        arguments: ["%t411%","@service_container"]
    transmission_manager:
        class: TorrentRequestBundle\Utils\TransmissionManager
        arguments: ["%transmission%","@service_container"]
    ifttt_manager_layla:
        class: TorrentRequestBundle\Utils\IFTTTManager
        arguments: ["%ifttt%","layla_key","@service_container"]
    ifttt_manager_lody:
        class: TorrentRequestBundle\Utils\IFTTTManager
        arguments: ["%ifttt%","lody_key","@service_container"]